# Generated by Django 3.1 on 2020-08-20 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=400)),
                ('slug', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=400)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('About', models.CharField(default='Its Good', max_length=1000)),
                ('Video', models.TextField(default='Not Available', max_length=500)),
                ('Image', models.ImageField(upload_to='media')),
                ('Cast', models.TextField(default='...', max_length=1000)),
                ('Rank', models.IntegerField()),
                ('MoviesGenre', multiselectfield.db.fields.MultiSelectField(choices=[('ACT', 'ACTION'), ('ADV', 'ADVENTURE'), ('COM', 'COMEDY'), ('CR', 'CRIME'), ('SCI-FY', 'SCI-FY'), ('ANI', 'ANIMATION'), ('HOR', 'HORROR'), ('SH', 'SUPERHERO'), ('DR', 'DRAMA')], max_length=35)),
                ('Status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('', 'Default')], max_length=200)),
                ('Field', models.CharField(choices=[('In Theatre 2020', 'In Theatre 2020'), ('Coming Soon', 'Coming Soon'), ('IMDB RATING', 'IMDB RATING')], max_length=200)),
                ('Imdb_rating', models.CharField(blank=True, default='Not Yet Rated', max_length=200)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Othermovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='media')),
                ('Rank', models.IntegerField()),
                ('Imdb_rating', models.FloatField()),
                ('MoviesGenre', multiselectfield.db.fields.MultiSelectField(choices=[('ACT', 'ACTION'), ('ADV', 'ADVENTURE'), ('COM', 'COMEDY'), ('CR', 'CRIME'), ('SCI-FY', 'SCI-FY'), ('ANI', 'ANIMATION'), ('HOR', 'HORROR'), ('SH', 'SUPERHERO'), ('DR', 'DRAMA')], max_length=35)),
                ('Status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('', 'Default')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TAPE_TITLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Imdb_rating', models.FloatField(blank=True)),
                ('Rotten_tomatoes_rating', models.FloatField(blank=True)),
                ('Rate_this_movie', models.FloatField(blank=True, max_length=300)),
                ('About', models.CharField(max_length=1000)),
                ('Cast', models.CharField(max_length=1000)),
                ('Release_date', models.IntegerField()),
                ('Status', models.CharField(choices=[('av', 'available'), ('N-av', 'Not-available')], max_length=100)),
                ('Image', models.ImageField(upload_to='media')),
                ('Genre', multiselectfield.db.fields.MultiSelectField(choices=[('ACT', 'ACTION'), ('ADV', 'ADVENTURE'), ('COM', 'COMEDY'), ('CR', 'CRIME'), ('SCI-FY', 'SCI-FY'), ('ANI', 'ANIMATION'), ('HOR', 'HORROR'), ('SH', 'SUPERHERO'), ('DR', 'DRAMA')], default='basic', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Trailers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='media')),
                ('Video', models.TextField(max_length=500)),
                ('Rank', models.IntegerField()),
                ('SeriesGenre', multiselectfield.db.fields.MultiSelectField(choices=[('ACT', 'ACTION'), ('ADV', 'ADVENTURE'), ('COM', 'COMEDY'), ('CR', 'CRIME'), ('SCI-FY', 'SCI-FY'), ('ANI', 'ANIMATION'), ('HOR', 'HORROR'), ('SH', 'SUPERHERO'), ('DR', 'DRAMA')], max_length=35)),
                ('Length', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tv1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('slug', models.CharField(default=1, max_length=500, unique=True)),
                ('Image', models.ImageField(upload_to='media')),
                ('About', models.CharField(default='Its Good', max_length=1000)),
                ('Cast', models.TextField(default='...', max_length=1000)),
                ('Rank', models.IntegerField()),
                ('Video', models.TextField(default='Not Available', max_length=500)),
                ('SeriesGenre', multiselectfield.db.fields.MultiSelectField(choices=[('ACT', 'ACTION'), ('ADV', 'ADVENTURE'), ('COM', 'COMEDY'), ('CR', 'CRIME'), ('SCI-FY', 'SCI-FY'), ('ANI', 'ANIMATION'), ('HOR', 'HORROR'), ('SH', 'SUPERHERO'), ('DR', 'DRAMA')], max_length=35)),
                ('Status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('', 'Default')], max_length=200)),
                ('Field', models.CharField(choices=[('POPULAR', 'POPULAR'), ('Coming Soon', 'Coming Soon'), ('RATING', 'IMDB RATING')], default=1, max_length=200)),
                ('Imdb_rating', models.CharField(blank=True, default='Not Yet Rated', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=1)),
                ('checkout', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
