# Generated by Django 3.1 on 2020-08-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('email', models.TextField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('Zip', models.CharField(max_length=500)),
                ('NameOnCard', models.CharField(max_length=500)),
                ('CCNumber', models.IntegerField()),
                ('ExpMonth', models.DateField()),
                ('ExpYear', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
