# Generated by Django 3.1 on 2020-08-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200822_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='Price',
        ),
    ]
