# Generated by Django 3.1 on 2020-08-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200822_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutForm',
            new_name='Checkout',
        ),
    ]
