# Generated by Django 3.1 on 2020-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200824_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='ExpMonth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='ExpYear',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
