# Generated by Django 3.1 on 2020-08-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200824_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('Zip', models.CharField(max_length=500)),
                ('NameOnCard', models.CharField(max_length=500)),
                ('CCNumber', models.IntegerField()),
                ('ExpMonth', models.CharField(max_length=20)),
                ('ExpYear', models.CharField(max_length=20)),
            ],
        ),
    ]
